feat: Worker as bluetooth remote device for BT tests
Enhance the Worker functionality by incorporating a function to enable
a LAVA-Worker Connect to pair a device during bluetooth test execution.
In order to get it works, the Worker should have a Bluetooth Dongle
device connected to a USB-port.

The function will work with the test from the
LAVA-test-definitions repository located here:
https://gitlab.com/revolutionpi/infrastructure/testing/
LAVA-test-definitions/automated/linux/bluetooth/bluetooth.sh.

Signed-off-by: Ramiro Gsponer <r.gsponer@kunbus.com>

diff --git a/worker/lib/utils b/worker/lib/utils
--- a/worker/lib/utils
+++ b/worker/lib/utils
@@ -1,4 +1,5 @@
 #!/bin/sh
+BT_DISCOVERY_TIMEOUT=120
 
 # Wait for the target to be down
 wait_for_reboot() {
@@ -22,6 +23,18 @@ wait_for_system_up() {
     while ! ping -c 1 "$1" > /dev/null 2>&1; do 
 	    sleep 1; 
     done
+}
+
+bluetooth_control() {
+    # shellcheck disable=SC3043
+    local param="$1"
+    if [ -z "${param}" ]; then
+        echo "Error: parameter for bluetoothctl not provided."
+        exit 1
+    fi
+    bluetoothctl discoverable-timeout "${BT_DISCOVERY_TIMEOUT}"
+    bluetoothctl pairable "${param}"
+    bluetoothctl discoverable "${param}"
 }
 
 # Check if a function is provided as the first argument
