feat: Add 'wait_for_ssh()' function
The 'wait_for_system_up()' function only waited for the DUT to respond
to ping after a reboot, which could lead to premature attempts to
access the device via SSH while the service was not fully available.

To fix this, a new function 'wait_for_ssh()' was added. This function
waits for the SSH service to be available by attempting an SSH
connection.
It uses the `ssh` command with `ConnectTimeout=5` to limit the
connection attempt to 5 seconds, `BatchMode=yes` to ensure no
interactive prompts (e.g., for passwords), and
`StrictHostKeyChecking=no` to bypass host key verification.

Signed-off-by: Ramiro Gsponer <r.gsponer@kunbus.com>

diff --git a/worker/lib/utils b/worker/lib/utils
--- a/worker/lib/utils
+++ b/worker/lib/utils
@@ -30,6 +30,22 @@ wait_for_system_up() {
     done
 }
 
+# wait for the SSH service to be available
+wait_for_ssh() {
+    if [ -z "$1" ]; then
+	    echo "Error: No IP address or target provided."
+	    exit 1
+    fi
+
+    while ! ssh -o ConnectTimeout=5 \
+                -o BatchMode=yes \
+                -o StrictHostKeyChecking=no \
+                "$1" exit > /dev/null 2>&1; do
+        sleep 1
+    done
+}
+
+
 bluetooth_control() {
     # shellcheck disable=SC3043
     local param="$1"
